Repository FC-SharedOffice-5/fe_sharedoffice, pull requests merged in 2024-06, with the labels that each got.

#58 마이페이지 마크업
  public/icons/default-image.svg
  public/icons/edit-icon.svg
  public/icons/go-icon.svg
  src/app/(mypage)/_components/input.tsx
  src/app/(mypage)/_components/list.tsx
  src/app/(mypage)/_components/status.tsx
  src/app/(mypage)/_components/title.tsx
  src/app/(mypage)/mypage/constants.ts
  src/app/(mypage)/mypage/edit/layout.tsx
  src/app/(mypage)/mypage/edit/page.tsx
  src/app/(mypage)/mypage/layout.tsx
  src/app/(mypage)/mypage/locker/layout.tsx
  src/app/(mypage)/mypage/locker/page.tsx
  src/app/(mypage)/mypage/office/layout.tsx
  src/app/(mypage)/mypage/office/page.tsx
  src/app/(mypage)/mypage/page.tsx
  src/app/(mypage)/mypage/supplies/layout.tsx
  src/app/(mypage)/mypage/supplies/page.tsx
  src/app/globals.css
  src/assets/icons/default-image.tsx
  src/assets/icons/edit-icon.tsx
  src/assets/icons/go-icon.tsx
Labels: design

#63 일정 생성 페이지 구현
  public/icons/add-member.svg
  public/icons/check-mark-white.svg
  public/icons/default-member.svg
  public/icons/delete-bg-gray.svg
  public/icons/toggle-off.svg
  src/app/(schedule)/schedule/_components/date-time-selector.tsx
  src/app/(schedule)/schedule/_components/decision-button.tsx
  src/app/(schedule)/schedule/_components/schedule-form.tsx
  src/app/(schedule)/schedule/add/layout.tsx
  src/app/(schedule)/schedule/add/page.tsx
  src/app/(schedule)/schedule/constants.ts
  src/components/mini-button.tsx
  src/components/schedule-time.tsx
  src/components/toggle.tsx
  src/utils/format-date.ts
  src/utils/format-time-input.ts
Labels: enhancement

#71 fix: error in schedule page
  next.config.mjs
  package-lock.json
  package.json
  public/detail_schedule_title.png
  public/member3.png
  public/member4.png
  public/member5.png
  public/member6.png
  public/member7.png
  public/member8.png
  src/app/(schedule)/schedule/[eventId]/attendees/constants.ts
  src/app/(schedule)/schedule/[eventId]/attendees/page.tsx
  src/app/(schedule)/schedule/[eventId]/page.tsx
  src/app/(schedule)/schedule/_components/date-time-selector.tsx
  src/app/(schedule)/schedule/_components/event-item.tsx
  src/app/(schedule)/schedule/_components/schedule-form.tsx
  src/app/(schedule)/schedule/_components/timeline.tsx
  src/app/(schedule)/schedule/add/attendees/constants.ts
  src/app/(schedule)/schedule/add/attendees/page.tsx
  src/app/(schedule)/schedule/page.tsx
  src/app/section.tsx
  src/components/accordion.tsx
  src/components/calendar.tsx
  src/components/monthly.tsx
  src/components/primary-button.tsx
  src/components/schedule-time.tsx
  src/components/weekly.tsx
  src/hooks/use-api-mutation.ts
  src/hooks/use-schedule.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/member-handlers.ts
  src/mocks/handlers/schedule-handlers.ts
  src/stores/schedule-store.ts
  src/types/data.ts
  src/types/schema.ts
  src/utils/api-function.ts
Labels: bug

#72 커뮤니티 메인 페이지 구현
  public/icons/comment.svg
  public/icons/floating-off.svg
  public/icons/floating-on.svg
  public/icons/hot.svg
  public/icons/like.svg
  public/icons/search.svg
  src/app/(community)/community/_component/board-add-modal.tsx
  src/app/(community)/community/_component/floating-button.tsx
  src/app/(community)/community/_component/free-board.tsx
  src/app/(community)/community/_component/office-select-modal.tsx
  src/app/(community)/community/_component/tab-section.tsx
  src/app/(community)/community/community-section.tsx
  src/app/(community)/community/layout.tsx
  src/app/(community)/community/page.tsx
  src/assets/icons/alarm-active-icon.tsx
  src/utils/format-date.ts
  tailwind.config.ts
Labels: enhancement

#74 커뮤니티 자유게시판 상세 페이지 구현
  public/memberDefault.png
  public/postImage1.png
  public/postImage2.png
  src/app/(community)/community/freeboards/[postId]/_components/comments.tsx
  src/app/(community)/community/freeboards/[postId]/_components/free-boards-post.tsx
  src/app/(community)/community/freeboards/[postId]/_components/input-comment.tsx
  src/app/(community)/community/freeboards/[postId]/_components/kebab-select-modal.tsx
  src/app/(community)/community/freeboards/[postId]/layout.tsx
  src/app/(community)/community/freeboards/[postId]/page.tsx
  src/app/(community)/community/freeboards/layout.tsx
  src/assets/icons/comment.tsx
  src/assets/icons/kebab.tsx
  src/assets/icons/like.tsx
  src/types/data.ts
  src/types/schema.ts
Labels: enhancement

#77 댓글 추가 기능 구현
  src/app/(community)/community/freeboards/[postId]/_components/comments.tsx
  src/app/(community)/community/freeboards/[postId]/_components/input-comment.tsx
  src/app/(community)/community/freeboards/[postId]/page.tsx
  src/types/schema.ts
Labels: enhancement

#85 오피스 페이지 더미 이미지 삽입
  public/date-filter.png
  public/filter.png
  public/icons/calendar-icon.svg
  public/icons/car-icon.svg
  public/icons/filter-icon.svg
  public/icons/people-icon.svg
  public/icons/x-line-icon.svg
  public/locker-after.png
  public/locker-before.png
  public/minimap.svg
  public/place.png
  src/app/(office)/office/[officeId]/page.tsx
  src/app/(office)/office/_components/locker.tsx
  src/app/(office)/office/_components/place.tsx
  src/app/(office)/office/detail/[officeId]/page.tsx
  src/app/(office)/office/layout.tsx
  src/app/(office)/office/locker/page.tsx
  src/app/(office)/office/reservation/page.tsx
  src/assets/icons/calendar-icon.tsx
  src/assets/icons/car-icon.tsx
  src/assets/icons/filter-icon.tsx
  src/assets/icons/people-icon.tsx
  src/assets/icons/x-line-icon.tsx
Labels: invalid
