Repository FC-SharedOffice-5/fe_sharedoffice, pull requests merged in 2024-05, with the labels that each got.

#3 Issue/PR 템플릿 업데이트
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: documentation

#11 tailwind 글로벌 스타일 적용
  public/fonts/PretendardVariable.woff2
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: chore

#14 Input 공통 컴포넌트 추가
  package-lock.json
  package.json
  src/app/globals.css
  src/components/text-input.tsx
Labels: design

#15 Button 공통 컴포넌트 추가
  src/app/globals.css
  src/components/primary-button.tsx
  src/components/text-input.tsx
  src/components/white-button.tsx
Labels: design

#18 로그인 기능 구현
  .eslintrc.json
  auth.ts
  package-lock.json
  package.json
  src/actions/auth.ts
  src/app/(user)/login/page.tsx
  src/app/page.tsx
  src/mocks/handlers/auth-handlers.ts
  src/types/next-auth.d.ts
Labels: enhancement

#20 비밀번호 찾기 페이지 마크업
  package-lock.json
  package.json
  public/arrow-login.svg
  public/delete.svg
  public/hide-off.svg
  public/hide.svg
  src/app/(login)/search-password/page.tsx
  src/app/globals.css
  src/components/primary-button.tsx
  src/components/text-input.tsx
  src/components/timer.tsx
  src/components/white-button.tsx
Labels: enhancement, design

#25 비밀번호 찾기 페이지 디자인 수정사항 반영
  public/warning.svg
  src/app/(auth)/new-password/complete/page.tsx
  src/app/(auth)/new-password/page.tsx
  src/app/(auth)/search-password/page.tsx
  src/components/primary-button.tsx
  src/components/timer-modal.tsx
  src/components/timer.tsx
Labels: design

#26 로그인 UI 구현
  .eslintrc.json
  auth.ts
  package-lock.json
  package.json
  public/icons/check-off.svg
  public/icons/check-on.svg
  public/icons/logo.svg
  src/actions/auth.ts
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/login/_components/NavLinkList.tsx
  src/app/(auth)/login/page.tsx
  src/app/(user)/login/page.tsx
  src/app/globals.css
  src/components/text-input.tsx
  src/mocks/handlers/auth-handlers.ts
  src/utils/validationSchemas.ts
Labels: design

#28 로그인 페이지 비밀번호 필드 수정사항 반영
  src/utils/validationSchemas.ts
Labels: design

#32 auth 관련 미들웨어 셋업
  package-lock.json
  package.json
  src/actions/auth.ts
  src/auth.ts
  src/middleware.ts
Labels: enhancement

#36 로그인 하위 네비게이션 버튼 3개 동작 추가 및 추가 동작 구현
  src/app/(auth)/login/_components/NavLinkList.tsx
  src/app/(auth)/signup/user-info/page.tsx
Labels: enhancement

#38 feat: update ui in search email page
  src/app/(auth)/search-email/complete/page.tsx
  src/app/(auth)/search-email/page.tsx
Labels: enhancement

#44 로그인 페이지 헤더 제거
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
Labels: design

#49 상태관리 라이브러리 zustand & react query 적용
  .eslintrc.json
  env.d.ts
  package-lock.json
  package.json
  src/actions/query-options.ts
  src/app/(auth)/signup/constants.ts
  src/app/(auth)/signup/email-verification/page.tsx
  src/app/(auth)/signup/last/page.tsx
  src/app/(auth)/signup/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/signup/password-nickname/page.tsx
  src/app/(auth)/signup/user-info/_components/gender-select-modal.tsx
  src/app/(auth)/signup/user-info/page.tsx
  src/app/(provider)/get-query-client.ts
  src/app/(provider)/react-query-provider.tsx
  src/app/(provider)/signup-provider.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/section.tsx
  src/auth.ts
  src/components/input.tsx
  src/mocks/handlers/auth-handlers.ts
  src/stores/signup-store.ts
  src/types/data.ts
  src/types/interface.ts
  src/types/schema.ts
Labels: enhancement

#51 일정 페이지 레이아웃 작업
  src/app/(schedule)/schedule/[eventId]/edit/page.tsx
  src/app/(schedule)/schedule/[eventId]/layout.tsx
  src/app/(schedule)/schedule/[eventId]/page.tsx
  src/app/(schedule)/schedule/_components/schedule-list.tsx
  src/app/(schedule)/schedule/add/layout.tsx
  src/app/(schedule)/schedule/add/page.tsx
  src/app/(schedule)/schedule/layout.tsx
  src/app/(schedule)/schedule/page.tsx
  src/assets/icons/schedule-add-icon.tsx
  src/components/calendar.tsx
  src/components/primary-button.tsx
Labels: design
